version: "3.9"

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - user-db
    env_file:
      - .env
    volumes:
      - ./services/user-service/config/config.yaml:/app/config.yaml
    environment:
      CONFIG_PATH: "/app/config.yaml"

  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_NAME}
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  band-service:
    build: ./services/band-service
    container_name: band-service
    ports:
      - "8082:8082"
    depends_on:
      - band-db
    env_file:
      - .env
    volumes:
      - ./services/band-service/config/config.yaml:/app/config.yaml
    environment:
      CONFIG_PATH: "/app/config.yaml"

  band-db:
    image: postgres:15
    container_name: band-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${BAND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BAND_POSTGRES_PASSWORD}
      POSTGRES_DB: band_db
    ports:
      - "5434:5432"
    volumes:
      - band-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  band-db-data:
