version: "3.9"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./services/user-service/config/config.yaml:/app/config.yaml
      - ./services/user-service/migrations:/app/migrations
    environment:
      CONFIG_PATH: "/app/config.yaml"
    command: >
      sh -c "goose -dir /app/migrations postgres 
      '$POSTGRES_CONN_STRING?sslmode=disable' up &&
      ./user-service"

  postgres:
    image: postgres:15
    container_name: user-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"