version: "3.9"

services:
  band-service:
    build: ./band-service
    container_name: band-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./services/band-service/config/config.yaml:/app/config.yaml
      - ./services/band-service/migrations:/app/migrations
    environment:
      CONFIG_PATH: "/app/config.yaml"
    command: >
      sh -c "goose -dir /app/migrations postgres 
      '$POSTGRES_CONN_STRING?sslmode=disable' up &&
      ./band-service"

  postgres:
    image: postgres:15
    container_name: band-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
