version: "3.9"

services:
  band-service:
    build: ./band-service
    container_name: band-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./services/band-service/config/config.yaml:/app/config.yaml
    environment:
      CONFIG_PATH: "/app/config.yaml"

  postgres:
    image: postgres:15
    container_name: band-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"